#Rendersnap
#Mon May 25 11:11:39 EEST 2026
behindCamMode=2
blockFaceCulling=true
chunkUpdateMode=1
entityCulling=true
fastLaunch=true
fluidOptimizer=true
fogOcclusion=true
fpsOverlayX=6
fpsOverlayY=6
hideMoon=false
hideSun=false
hideWeather=false
lightingChunkTrim=true
multiRender=true
occlusionCulling=true
showFpsOverlay=true
textureLod=true
zoomTransition=2
